# =============================================================================
# Configuratie voor automatische padelbaan reservering - TPV Heksenwiel
# Bijgewerkt via het dashboard op 11-2-2026, 16:32:23
# =============================================================================

credentials:
  login_type: bondsnummer
  username: ""
  password: ""
reservering:
  dagen:
    - dag: 1
      tijden:
        - "20:30"
        - "21:30"
    - dag: 6
      tijden:
        - "19:30"
        - "20:30"
  uren_vooruit: 48
  baan_voorkeur:
    - 1
    - 3
    - 4
    - 2
  duur_minuten: 60
medespelers:
  standaard_spelers:
    - Ruud van Erp
    - Rick Maat
    - Ron Spaans
  spelers_per_dag:
    "1":
      - Ruud van Erp
      - Rick Maat
      - Ron Spaans
    "6":
      - Ruud van Erp
      - Rick Maat
      - Eric-jan Verdaasdonk
email:
  enabled: true
  smtp_server: smtp.gmail.com
  smtp_port: 587
  use_tls: true
  afzender: martijn.vermolen85@gmail.com
  afzender_wachtwoord: ""
  ontvanger: martijn.vermolen85@gmail.com
urls:
  login: https://tpv-heksenwiel.knltb.site/mijn?onlyProfileComponents=True
  reservering: https://tpv-heksenwiel.knltb.site/me/ReservationsPlayers
browser:
  headless: true
  slow_mo: 0
  timeout: 30000
